<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.7 ../../../../static/models/marker.glb -T
-->

<script lang="ts">
  import { T } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";
  import type { Snippet } from "svelte";

  interface Props {
    fallback?: Snippet;
    error?: Snippet<[any]>;
    children?: Snippet<[any]>;
    [key: string]: any;
  }

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props = $props();

  const gltf = useGltf("/models/marker.glb", { dracoLoader: useDraco() });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group>
      <T.Mesh
        geometry={gltf.nodes["Node-Mesh003"].geometry}
        material={gltf.materials.mat8}
      />
      <T.Mesh
        geometry={gltf.nodes["Node-Mesh003_1"].geometry}
        material={gltf.materials.mat23}
      >
        <T.PointLight
          position={[-1, 0.8, 0]}
          color="#ffffff"
          intensity={3}
        ></T.PointLight>
        <T.PointLight
          position={[1, 0.8, 0]}
          color="#ffffff"
          intensity={3}
        ></T.PointLight></T.Mesh
      >
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
