<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.7 ../../../../static/models/sun.glb -T
-->

<script lang="ts">
  import { T } from "@threlte/core";
  import { useDraco, useGltf } from "@threlte/extras";
  import type { Snippet } from "svelte";

  interface Props {
    lightIntesity?: number;
    fallback?: Snippet;
    error?: Snippet<[any]>;
    children?: Snippet<[any]>;
    [key: string]: any;
  }

  let {
    lightIntesity = 7,
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props = $props();

  const gltf = useGltf("/models/sun.glb", { dracoLoader: useDraco() });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.GeoSphere003_1.geometry}
      material={gltf.materials._Sol02___Default}
    />
    <T.Mesh
      geometry={gltf.nodes.GeoSphere003_1_1.geometry}
      material={gltf.materials._Sol01___Default}
    ></T.Mesh>
    <T.SpotLight
      decay={0}
      position={[20, 45, 80]}
      target={ref}
      intensity={lightIntesity}
    ></T.SpotLight>
    <T.SpotLight
      decay={0}
      position={[0, 65, 80]}
      target={ref}
      intensity={lightIntesity}
    ></T.SpotLight>
    <T.SpotLight
      decay={0}
      position={[-20, 45, 80]}
      target={ref}
      intensity={lightIntesity}
    ></T.SpotLight>
    <T.SpotLight
      decay={0}
      position={[0, 25, 80]}
      target={ref}
      intensity={lightIntesity}
    ></T.SpotLight>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
